### ISSUE TITLE
Docker can't start. Problem with user creds and iptables

### ISSUE THREAD

**Issue by bmarohl** [bubuntux/nordvpn#102]
User and pass are functional, I have full use of the VPN on other devices.
I'm trying to run this on a Synology DS918+ configuring with Portainer

Compose: 
version: "2"
services:
  vpn:
    image: bubuntux/nordvpn:latest
    container_name: Stack_NordVPN
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    environment:
      - USER=user
      - PASS=pass
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=10.1.10.0/24
      - FIREWALL=1

LOGS:
iptables v1.8.2 (legacy): Couldn't load match `owner':No such file or directory,
,
Try `iptables -h' or 'iptables --help' for more information.,

-
  

-
\
|
/
-
\
|
/
-
  
Username or password is not correct. Please try again.,
Technology is successfully set to 'NordLynx'.,
Subnet 172.20.0.0/16 is whitelisted successfully.,

-
  
Please enter your login details.,
Stdin/Stdout should be terminal,

**Comment by bubuntux** [comment]
review https://github.com/bubuntux/nordvpn/wiki/Troubleshooting 
check for special characters on your password

**Comment by bmarohl** [comment]
The password for my nord account, at least the provided internal account for actual use is just a long alpha numeric string, no specials just upper lower and numbers.

**Comment by stephanpieri** [comment]
I have the same issue as OP.

I actually had a '$' at the start of my password, however to rule out this as a environment variable, I changed the password to include an exclamation mark (!) instead.

My docker compose is as follows (fields redacted)
`services:
    NordLynx:
        image: bubuntux/nordvpn:latest
        container_name: media-nordlynx
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        devices:
            - /dev/net/tun
        network_mode: bridge
        sysctls:
            - net.ipv4.conf.all.rp_filter=2
        environment:
            - USER=******@******.com
            - PASS=*******!*********
            - TECHNOLOGY=OpenVPN
            - DNS=1.1.1.1,1.0.0.1
            - NETWORK=10.0.0.0/16
            - TZ=Europe/London
            - DEBUG=on
        ports:
            - 9091:9091
        restart: unless-stopped`

The above is based on the latest examples on docker and github.

Server is a Synology DS918+ and it used to work previously, albeit DSM has since had an update. But I seem to be getting the **iptables v1.8.2 (legacy): Couldn't load match `owner':No such file or directory** issue. I've double and triple checked my credentials and they are good.

**Comment by bmarohl** [comment]
Months go by without response(FYI I had the exact same error on the same hardware), that's why I changed over to azinchen/nordvpn on a DS918+ using portainer and a single stack with 10 dockers in my compose and haven't looked back until your comment.

**Comment by Minimad-Diver** [comment]
I only just started looking at trying to use this docker on a Synology (DSM 6.2.3), but I've found that the error "iptables v1.8.2 (legacy): Couldn't load match `owner':No such file or directory" is caused by a kernel module 'xt_owner' that's missing from DSM 6.2.3.  I'm looking to see if I can compile it somehow.

**Comment by bmarohl** [comment]
Sorry to post a solution outside this project, but after months of no solution it felt right to let others know there was a functional system for Nord and Synology dockers.

**Comment by cyrus1977** [comment]
Same issue for me. I tried using a raspberry and syno ds920 no luck.

**Comment by bubuntux** [comment]
i removed the owner matching iptable rules, that may solve this issue, please reopen if it doesn't  please reopen
