### ISSUE TITLE
Is there a way to open the daemon

### ISSUE THREAD

**Issue by NurdTurd** [bubuntux/nordvpn#11]
Is there a way to open up the daemon port from the vpn container? I'd like to connect to it with my thin client, but by the looks of it, it's enclosed in the vpn container.

**Comment by bubuntux** [comment]
not sure what you mean by daemon port? what exactly are you trying to do ?

**Comment by NurdTurd** [comment]
I made this issue in the wrong repo, my bad, but you might be able to help me anyways.

How would I open up a TCP port that is being enclosed in the VPN container from another container.

I have Deluge running in conjunction with your `nordvpn` container, and it closes all ports, so I was wondering if it is possible to leak/open up a port that is enclosed within the `nordvpn` container.

**Comment by bubuntux** [comment]
check the documentation here, you can specify a network (something like 192.168.1.0/24) so everything coming from that network into the container will responda back otherwise everything will remain enclosed in the container, take a look at the examples, 
nordvpn container runs with NET_ADMIN, export all the need it ports and also define the network, then the second container just define that is going to use the nordvpn network.
