### ISSUE TITLE
Healthcheck in NordVPN container

### ISSUE THREAD

**Issue by flipyou** [bubuntux/nordvpn#27]
I have several containers which depend on the NordVPN container to have a successful connection and the network all set up.  If they start too quickly sometimes I have to restart them after NordVPN is running.  This means that on a reboot I can't rely on all my containers simply working.

Could you include code in the container for a Healthcheck?  This would allow me to use Healthcheck code in my docker-compose file to stop containers if the VPN is dropped or not not yet ready, and to restart containers when the VPN is up again.

I considered writing a bunch of scripts to start and stop various containers at the right times, but incorporating Healthcheck would be much simpler.

here's a link to the documentation https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by bubuntux** [comment]
The image used to have the [helthcheck ](https://github.com/bubuntux/nordvpn/commit/182573b4c87d89e3b5c9c600ce90d34f9d4cae35#diff-3254677a7917c6c01f55212f86c57fbf) i removed because is actually checking if the connection is up and not necessarily if the service is up, there's a small diff there. i haven't find a proper healthcheck that i like.

Anyway you can manually add one thought [command line](https://docs.docker.com/engine/reference/run/#healthcheck) or [docker-compose ](https://docs.docker.com/compose/compose-file/#healthcheck) to fulfill your needs 

please consider creating merge request with a heatlcheck if you find one generic enough, thanks!

**Comment by bubuntux** [comment]
also.. is just setup using docker-compose? 
if so i believe the dependent components will wait until the nordvpn container is up and ready

**Comment by stickystyle** [comment]
FYI - this is the healthcheck I use in my docker-compose, it just checks if the tunnel is up; better than nothing I suppose. 

```
    healthcheck:
      test: "ifconfig | grep ^tun0 > /dev/null"
      interval: 15s
      timeout: 1s
```
