### ISSUE TITLE
No internet access for whole NAS when container active

### ISSUE THREAD

**Issue by AKDub** [bubuntux/nordvpn#34]
**Describe the bug**
This is probably a simple one, but I am new to all this. Basically when I enable the container internet access for all the other containers and the host (a NAS running openmediavault) stops

**To Reproduce**
created through the openmediavault GUI. Will upload screenshot if needed.

**Comment by bubuntux** [comment]
not enough information.. what is the issue? how is the issue related to this container? what are the docker commands used ?

**Comment by Groofster** [comment]
You probably selected network-mode 'host' which will do exactly what you describe here. It will create a VPN connection for your NAS itself and since all your other containers are depending on the network of the host (NAS) they all lose internet.

Try selecting the bridged or nat'ed network instead for the vpn container.
